[project]
name = "test-july"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polyfactory>=2.22.0",
    "pytest>=8.4.1",
    "ruff==0.12.2",
]
